def register_blueprints(
    *,
    app,
    create_settings_blueprint,
    create_epg_blueprint,
    create_portal_blueprint,
    create_editor_blueprint,
    create_misc_blueprint,
    create_hdhr_blueprint,
    create_playlist_blueprint,
    create_streaming_blueprint,
    job_manager,
    refresh_xmltv,
    refresh_xmltv_for_epg_ids,
    refresh_xmltv_for_portal,
    get_cached_xmltv,
    get_last_updated,
    get_epg_refresh_status,
    logger,
    getPortals,
    get_db_connection,
    effective_epg_name,
    getSettings,
    open_epg_source_db,
    savePortals,
    ACTIVE_GROUP_CONDITION,
    channelsdvr_match_status,
    channelsdvr_match_status_lock,
    normalize_mac_data,
    defaultPortal,
    DB_PATH,
    set_cached_xmltv,
    filter_cache,
    get_epg_channel_ids,
    get_epg_channel_map,
    suggest_channelsdvr_matches,
    host,
    refresh_lineup,
    set_last_playlist_host,
    refresh_custom_sources,
    LOG_DIR,
    occupied,
    get_cached_lineup,
    effective_display_name,
    get_cached_playlist,
    set_cached_playlist,
    get_last_playlist_host,
    moveMac,
    score_mac_for_selection,
    hls_manager,
):
    app.register_blueprint(create_settings_blueprint(job_manager.enqueue_epg_refresh))
    app.register_blueprint(
        create_epg_blueprint(
            refresh_xmltv=refresh_xmltv,
            refresh_epg_for_ids=refresh_xmltv_for_epg_ids,
            enqueue_epg_refresh=job_manager.enqueue_epg_refresh,
            get_cached_xmltv=get_cached_xmltv,
            get_last_updated=get_last_updated,
            get_epg_refresh_status=get_epg_refresh_status,
            logger=logger,
            getPortals=getPortals,
            get_db_connection=get_db_connection,
            effective_epg_name=effective_epg_name,
            getSettings=getSettings,
            open_epg_source_db=open_epg_source_db,
        )
    )
    app.register_blueprint(
        create_portal_blueprint(
            logger=logger,
            getPortals=getPortals,
            savePortals=savePortals,
            getSettings=getSettings,
            get_db_connection=get_db_connection,
            ACTIVE_GROUP_CONDITION=ACTIVE_GROUP_CONDITION,
            channelsdvr_match_status=channelsdvr_match_status,
            channelsdvr_match_status_lock=channelsdvr_match_status_lock,
            normalize_mac_data=normalize_mac_data,
            job_manager=job_manager,
            defaultPortal=defaultPortal,
            DB_PATH=DB_PATH,
            set_cached_xmltv=set_cached_xmltv,
            filter_cache=filter_cache,
        )
    )
    app.register_blueprint(
        create_editor_blueprint(
            logger=logger,
            get_db_connection=get_db_connection,
            ACTIVE_GROUP_CONDITION=ACTIVE_GROUP_CONDITION,
            get_cached_xmltv=get_cached_xmltv,
            get_epg_channel_ids=get_epg_channel_ids,
            get_epg_channel_map=get_epg_channel_map,
            getSettings=getSettings,
            suggest_channelsdvr_matches=suggest_channelsdvr_matches,
            host=host,
            refresh_epg_for_ids=refresh_xmltv_for_epg_ids,
            refresh_lineup=refresh_lineup,
            enqueue_refresh_all=job_manager.enqueue_refresh_all,
            set_last_playlist_host=set_last_playlist_host,
            filter_cache=filter_cache,
            effective_epg_name=effective_epg_name,
        )
    )
    app.register_blueprint(
        create_misc_blueprint(
            LOG_DIR=LOG_DIR,
            occupied=occupied,
            refresh_custom_sources=refresh_custom_sources,
        )
    )
    app.register_blueprint(
        create_hdhr_blueprint(
            host=host,
            getSettings=getSettings,
            refresh_lineup=refresh_lineup,
            get_cached_lineup=get_cached_lineup,
        )
    )
    app.register_blueprint(
        create_playlist_blueprint(
            logger=logger,
            host=host,
            getSettings=getSettings,
            get_db_connection=get_db_connection,
            ACTIVE_GROUP_CONDITION=ACTIVE_GROUP_CONDITION,
            effective_display_name=effective_display_name,
            effective_epg_name=effective_epg_name,
            get_cached_playlist=get_cached_playlist,
            set_cached_playlist=set_cached_playlist,
            get_last_playlist_host=get_last_playlist_host,
            set_last_playlist_host=set_last_playlist_host,
        )
    )
    app.register_blueprint(
        create_streaming_blueprint(
            logger=logger,
            getPortals=getPortals,
            getSettings=getSettings,
            get_db_connection=get_db_connection,
            moveMac=moveMac,
            score_mac_for_selection=score_mac_for_selection,
            occupied=occupied,
            hls_manager=hls_manager,
        )
    )
