def register_blueprints(*, app, state):
    app.register_blueprint(state.create_settings_blueprint(state.job_manager.enqueue_epg_refresh))
    app.register_blueprint(
        state.create_epg_blueprint(
            refresh_xmltv=state.refresh_xmltv,
            refresh_epg_for_ids=state.refresh_xmltv_for_epg_ids,
            enqueue_epg_refresh=state.job_manager.enqueue_epg_refresh,
            get_cached_xmltv=state.get_cached_xmltv,
            get_last_updated=state.get_last_updated,
            get_epg_refresh_status=state.get_epg_refresh_status,
            logger=state.logger,
            getPortals=state.getPortals,
            get_db_connection=state.get_db_connection,
            effective_epg_name=state.effective_epg_name,
            getSettings=state.getSettings,
            open_epg_source_db=state.open_epg_source_db,
        )
    )
    app.register_blueprint(
        state.create_portal_blueprint(
            logger=state.logger,
            getPortals=state.getPortals,
            savePortals=state.savePortals,
            getSettings=state.getSettings,
            get_db_connection=state.get_db_connection,
            ACTIVE_GROUP_CONDITION=state.ACTIVE_GROUP_CONDITION,
            channelsdvr_match_status=state.channelsdvr_match_status,
            channelsdvr_match_status_lock=state.channelsdvr_match_status_lock,
            normalize_mac_data=state.normalize_mac_data,
            job_manager=state.job_manager,
            defaultPortal=state.defaultPortal,
            DB_PATH=state.DB_PATH,
            set_cached_xmltv=state.set_cached_xmltv,
            filter_cache=state.filter_cache,
        )
    )
    app.register_blueprint(
        state.create_editor_blueprint(
            logger=state.logger,
            get_db_connection=state.get_db_connection,
            ACTIVE_GROUP_CONDITION=state.ACTIVE_GROUP_CONDITION,
            get_cached_xmltv=state.get_cached_xmltv,
            get_epg_channel_ids=state.get_epg_channel_ids,
            get_epg_channel_map=state.get_epg_channel_map,
            getSettings=state.getSettings,
            suggest_channelsdvr_matches=state.suggest_channelsdvr_matches,
            host=state.host,
            refresh_epg_for_ids=state.refresh_xmltv_for_epg_ids,
            refresh_lineup=state.refresh_lineup,
            enqueue_refresh_all=state.job_manager.enqueue_refresh_all,
            set_last_playlist_host=state.set_last_playlist_host,
            filter_cache=state.filter_cache,
            effective_epg_name=state.effective_epg_name,
        )
    )
    app.register_blueprint(
        state.create_misc_blueprint(
            LOG_DIR=state.LOG_DIR,
            occupied=state.occupied,
            refresh_custom_sources=state.refresh_custom_sources,
        )
    )
    app.register_blueprint(
        state.create_hdhr_blueprint(
            host=state.host,
            getSettings=state.getSettings,
            refresh_lineup=state.refresh_lineup,
            get_cached_lineup=state.get_cached_lineup,
        )
    )
    app.register_blueprint(
        state.create_playlist_blueprint(
            logger=state.logger,
            host=state.host,
            getSettings=state.getSettings,
            get_db_connection=state.get_db_connection,
            ACTIVE_GROUP_CONDITION=state.ACTIVE_GROUP_CONDITION,
            effective_display_name=state.effective_display_name,
            effective_epg_name=state.effective_epg_name,
            get_cached_playlist=state.get_cached_playlist,
            set_cached_playlist=state.set_cached_playlist,
            get_last_playlist_host=state.get_last_playlist_host,
            set_last_playlist_host=state.set_last_playlist_host,
        )
    )
    app.register_blueprint(
        state.create_streaming_blueprint(
            logger=state.logger,
            getPortals=state.getPortals,
            getSettings=state.getSettings,
            get_db_connection=state.get_db_connection,
            moveMac=state.moveMac,
            score_mac_for_selection=state.score_mac_for_selection,
            occupied=state.occupied,
            hls_manager=state.hls_manager,
        )
    )
